name: boostpython_pyodide

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  build_and_test:
    name: Builds and test Pyodide wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
      - name: Cache environment
        id: cache-build-env
        uses: actions/cache@v4
        with:
          path: build_env
          key: build_env_cache
      - name: Set up environment
        if: ${{ steps.cache-build-env.outputs.cache-hit != 'true' }}
        run: |
          ./setup_emsdk_env.sh
      - name: Build
        run: |
          if [[ $($MAMBA_EXE env list | grep ems) -eq "" ]]; then
            $MAMBA_EXE create -n ems -c conda-forge python=3.12 cmake pyodide-build boost
          fi
          eval "$($MAMBA_EXE shell activate ems)"
          source build_env/emsdk/emsdk_env.sh
          pyodide build
      - name: Test
        run: |
          eval "$($MAMBA_EXE shell activate ems)"
          npm install
          npm test
