name: boostpython_pyodide

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  build_and_test:
    name: Builds and test Pyodide wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
      - name: Build
        run: |
          $MAMBA_EXE create -n ems -c conda-forge python=3.12 cmake pyodide-build
          eval "$($MAMBA_EXE shell activate ems)"
          export PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install ${PYODIDE_EMSCRIPTEN_VERSION}
          ./emsdk activate ${PYODIDE_EMSCRIPTEN_VERSION}
          source emsdk/emsdk_env.sh
          pyodide build
      - name: Test
        run: |
          eval "$($MAMBA_EXE shell activate ems)"
          npm install
          npm test
